### ISSUE TITLE
The request for the source code of paper "Deep Joint Source-Channel Coding for Wireless Image Transmission"

### ISSUE THREAD

**Issue by ZJU-XWK** [kurka/deepJSCC-feedback#1]
Recently I  did my work to reproduce  the results in your paper named "Deep Joint Source-Channel Coding for Wireless Image Transmission". But I didn't succeed. So I really hope that you could share your source code about the paper. Thank you very much.

**Comment by kurka** [comment]
if you use the code in this repository setting `n_layers=1`, it will discard the feedback layers and work as in the original DeepJSCC paper.

**Comment by xwk111** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Monte2345** [comment]
Even though I set n_layers=1, I still can't reproduce the result as good as your work.

**Comment by ZJU-XWK** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
